package vnua.fita.bookstore.util;

public class Constant {
    public static final String BOOK_ID_INVALID_VALIDATE_MSG = "Mã sách không hợp lệ"; 
    public static final String BOOK_QUANTITY_IN_STOCK_INVALID_VALIDATE_MSG = "Số lượng sách trong kho không hợp lệ"; 
    public static final String ADD_TO_CART_ACTION = "addToCart"; 
    public static final String ADD_ORDER_ERROR_MSG = "Lỗi khi thêm đơn hàng"; 
    public static final String NOT_ENOUGH_ORDER_ERROR_MSG = "Không đủ hàng"; 
    public static final String CART_OF_CUSTOMER = "cartOfCustomer"; 
    public static final String ORDER_OF_CUSTOMER = "orderOfCustomer"; 
    public static final String REMOVE_FROM_CART_ACTION = "removeFromCart"; 
    public static final String GET_BOOK_FAIL = "Lỗi khi lấy danh sách sách"; 
    public static final String INCORRECT_ACCOUNT_VALIDATE_MSG = "Thông tin tài khoản không chính xác"; 
    public static final int ADMIN_ROLE = 1; 
    public static final int CUSTOMER_ROLE = 2; 
    public static final String USERNAME_EMPTY_VALIDATE_MSG = "Vui lòng nhập tên đăng nhập"; 
    public static final String PASSWORD_EMPTY_VALIDATE_MSG = "Vui lòng nhập mật khẩu"; 
    public static final String LOGINED_USER = "loginedUser";
    public static final String USERNAME_STORE_IN_COOKIE_OF_BOOKSTORE = "username";
    public static final String TOKEN_STORE_IN_COOKIE_OF_BOOKSTORE = "token";
    public static final String SECRET_STRING = "SECRET_STRING";
    public static final String INSERT_BOOK_FAIL = "Lỗi khi thêm sách mới";
    public static final String CASH_PAYMENT_MODE = "cash";
    public static final String TRANSFER_PAYMENT_MODE = "transfer";
    public static final byte WAITING_CONFIRM_ORDER_STATUS = 1;
    public static final byte DELEVERING_ORDER_STATUS = 2;
    public static final byte DELIVERED_ORDER_STATUS = 3;
    public static final byte CANCEL_ORDER_STATUS = 4;
    public static final byte REJECT_ORDER_STATUS = 5;
    public static final byte NOT_AVAILABLE_ORDER_STATUS = 6;
    public static final String PAYMENTED_STATUS = "Đã thanh toán";
    public static final String UNPAYMENTED_STATUS = "Chưa thanh toán";
    public static final String DELIVERY_ADDRESS_EMPTY_VALIDATE_MSG = "Vui lòng nhập địa chỉ giao hàng";
    public static final String TRANSFER_IMAGE_EMPTY_MSG = "Vui lòng chọn ảnh chuyển khoản";
    public static final String ORDER_LIST_OF_CUSTOMER = "orderListOfCustomer";
    public static final String WAITING_APPROVE_ACTION = "waiting";
    public static final String DELIVERING_ACTION = "delivering";
    public static final String DELIVERED_ACTION = "delivered";
    public static final String REJECT_ACTION = "reject";
    public static final String UPDATE_ORDER_SUCCESS = "Cập nhật đơn hàng thành công";
    public static final String UPDATE_ORDER_FAIL = "Cập nhật đơn hàng thất bại";
    public static final byte DELIVERING_ORDER_STATUS = 2;
    public static final String ORDER_ID_INVALID_VALIDATE_MSG = "Mã đơn hàng không hợp lệ";
    public static final String VALUE_INVALID_VALIDATE_MSG = "Giá trị không hợp lệ";
}
